
spring:

  application:
    name: JPA-Hibernate-Study

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect


  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: false


