
server:
  port: 8080

logging:
  level:
    # Enable debug-level logging for Spring Security
    org.springframework.security: DEBUG

    # Enable logging for specific components (optional)
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.authentication.logout: DEBUG
    org.springframework.security.config: DEBUG



