
server:
  port: 8080

logging:
  level:
    # Enable debug-level logging for Spring Security
    org.springframework.security: DEBUG

    # Enable logging for specific components (optional)
    org.springframework.security.authentication: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.authentication.logout: DEBUG
    org.springframework.security.config: DEBUG

spring:

  application:
    name: backend

  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: '4fabb1b5-e1cd-4f2a-8ef5-ce09a8804b21'
            client-secret:
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/"
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/a25fff9c-3f63-4fb2-9a8a-d9bdd0321f9a/v2.0

